### ISSUE TITLE
Cookie Monster loads wrong

### ISSUE THREAD

**Issue by Aless-OP** [klattmose/CookieClickerModManager#9]
I use Cookie Monster and some other mods (CCSE, Horticookie, Idle Trading, Auto JQB). When they're loaded, they're all fine, except Cookie Monster. It loads with the default settings instead of loading with mine, also, all the features related to colors, such as flashes, just don't work or they're always white. Is it the mod manager or am I doing something wrong?

**Comment by klattmose** [comment]
Unlikely to be the Mod Manager itself, but there are steps you can do to narrow down where the problem might be. Try doing the following steps:

1. Load the game.
2. Change a Cookie Monster setting.
3. Save the game (Ctrl-S or just wait 60 seconds)
4. Reload the game.
5. Check the setting you just changed.

Do those steps in each of the following scenarios:

1. With your normal mod setup.
2. With only Cookie Monster enabled.
3. With the Mod Manager disabled entirely (load Cookie Monster manually)


If the problem goes away in scenario 1, everything is fine and there was a mistake in your testing method.
If the problem goes away in scenario 2, there is a mod conflict. Enable the other mods one at a time to isolate which mod is conflicting with it.
If the problem goes away in scenario 3, then the problem is with the Mod Manager.
If the problem doesn't go away, then the problem is with Cookie Monster itself.

Let me know how it goes.

**Comment by Aless-OP** [comment]
Trying that I accidentally fixed it. If I disable CCSE the game freezes, if Cookie Monster is ordered after CCSE it loads without the settings and with the colors bugged, then I tried to put Cookie Monster the last of them and it worked! For some reason the problem was that Cookie Monster loads right after CCSE, and for some other strange reason, CCSE needs to load besides even if others like Horticookie loads it automatically. Thank you for the help, I appreciate it.
